# install.packages("devtools")
#devtools::install_github("UrbanInstitute/urbnmapr")
# install.packages("ggpubr")
library(dplyr)
library(shiny)
library(stringr)
library(tidyverse)
library(sf)
library(markdown)
library(DT)
library(httr)
library(jsonlite)
library(scales)
library(nasapower)